### ISSUE TITLE
Add basic Redux structure

### ISSUE THREAD

**Issue by SrDevDash** [EXPRESSFOOD2/storeclient#2]
Esto es para mañana empezar a implementar cada action

**Comment by SrDevDash** [comment]
Queremos que en los redux manejemos un poco las carpetas @jfernandez141 para cada cosa, aparte tener un archivo aparte para los tipos 
![image](https://user-images.githubusercontent.com/62898809/218848480-6aeb36e8-e310-44e0-8472-4e872057b49c.png)

**Comment by SrDevDash** [comment]
Debería estar así 
![image](https://user-images.githubusercontent.com/62898809/218848650-0c997eed-f8fd-4fd5-b556-099165088ee1.png)
![image](https://user-images.githubusercontent.com/62898809/218848683-9294ffc4-e86a-4df9-b7d7-6f53da8aa9fb.png)

**Comment by jfernandez141** [comment]
Listo ya lo modifico
