### ISSUE TITLE
Login Logic

### ISSUE THREAD

**Issue by SrDevDash** [EXPRESSFOOD2/storeclient#62]
- Implementar el redux con la ruta de login para loguearte

- Guardar el token en local store

- Proteger las rutas si no estas logueado

- Si no estas logueado te va a mandar al login

**Comment by jfernandez141** [comment]
En la ruta /users/login del back, se hace la validación con account_name no con email.

**Comment by jfernandez141** [comment]
Falta : Guardar el token en local store

Proteger las rutas si no estas logueado

**Comment by jfernandez141** [comment]
DONE
